export const EDITOR_REQUEST = "EDITOR_REQUEST"
export const EDITOR_RESPONSE = "EDITOR_RESPONSE"
export const POST_ADD = "POST_ADD"
export const POST_UPDATE = "POST_UPDATE"

export const POST_REQUEST = "POST_REQUEST"
export const POST_RESPONSE = "POST_RESPONSE"

export const APP_LOAD_REQUEST = "APP_LOAD_REQUEST"
export const APP_LOAD_RESPONSE = "APP_LOAD_RESPONSE"

export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_RESPONSE = "AUTH_RESPONSE"

export const SETTINGS_REQUEST = "SETTINGS_REQUEST"
export const SETTINGS_RESPONSE = "SETTINGS_RESPONSE"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_RESPONSE = "PROFILE_RESPONSE"

export const POSTS_REQUEST = "POSTS_REQUEST"
export const POSTS_RESPONSE = "POSTS_RESPONSE"

//POSTS ASYNCH  REQUEST TYPES:
export const ALL = "ALL"
export const FOLLOW = "FOLLOW"
export const FAVOURITE = "FAVOURITE"

//POSTS ASYNCH REQUEST TYPES:
export const POSTS_REQUEST_TYPES = {
    ALL,
    FOLLOW,
    FAVOURITE
}

export const EDITOR = {
    POST_ADD,
    POST_UPDATE,
    EDITOR_REQUEST,
    EDITOR_RESPONSE
}

export const AUTH = {
    AUTH_REQUEST,
    AUTH_RESPONSE
}

export const APP = {
    APP_LOAD_REQUEST,
    APP_LOAD_RESPONSE
}

export const SETTINGS = {
    SETTINGS_REQUEST,
    SETTINGS_RESPONSE
}

export const PROFILE = {
    PROFILE_REQUEST,
    PROFILE_RESPONSE
}

export const POSTS = {
    POSTS_REQUEST,
    POSTS_RESPONSE
}