export const POST_ADD = "POST_ADD"
export const POST_UPDATE = "POST_UPDATE"

export const APP_LOAD_REQUEST = "APP_LOAD_REQUEST"
export const APP_LOAD_RESPONSE = "APP_LOAD_RESPONSE"

export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_RESPONSE = "AUTH_RESPONSE"

export const SETTINGS_REQUEST = "SETTINGS_REQUEST"
export const SETTINGS_RESPONSE = "SETTINGS_RESPONSE"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_RESPONSE = "PROFILE_RESPONSE"

export const POSTS_REQUEST = "POSTS_REQUEST"
export const POSTS_RESPONSE = "POSTS_RESPONSE"

export const EDITOR = {
    POST_ADD,
    POST_UPDATE
}

export const AUTH = {
    AUTH_REQUEST,
    AUTH_RESPONSE,
}

export const APP = {
    APP_LOAD_REQUEST,
    APP_LOAD_RESPONSE
}

export const SETTINGS = {
    SETTINGS_REQUEST,
    SETTINGS_RESPONSE
}

export const PROFILE = {
    PROFILE_REQUEST,
    PROFILE_RESPONSE
}

export const POSTS = {
    POSTS_REQUEST,
    POSTS_RESPONSE
}